import type { BoatClass } from './types'

export type ApparentWind = {
  angle: number
  speed: number
}

export type MainTrimMode = 'class-guide' | 'transition' | 'attached-flow' | 'shroud-limit'

export type MainTrimSolution = {
  apparentWind: ApparentWind
  boomAngle: number
  flowBoomAngle: number
  targetAngleOfAttack: number
  mode: MainTrimMode
  label: string
}

const clamp = (value: number, min: number, max: number) =>
  Math.min(max, Math.max(min, value))

const lerp = (start: number, end: number, amount: number) =>
  start + (end - start) * amount

const inverseLerp = (start: number, end: number, value: number) =>
  clamp((value - start) / (end - start), 0, 1)

const smoothstep = (start: number, end: number, value: number) => {
  const amount = inverseLerp(start, end, value)
  return amount * amount * (3 - 2 * amount)
}

/**
 * Combines true wind and the headwind generated by boat speed.
 * Angles are measured from the bow on one tack and speeds use the same unit.
 */
export function apparentWind(
  trueWindAngle: number,
  trueWindSpeed: number,
  boatSpeed: number,
): ApparentWind {
  const radians = (clamp(trueWindAngle, 0, 180) * Math.PI) / 180
  const along = Math.max(0, trueWindSpeed) * Math.cos(radians) + Math.max(0, boatSpeed)
  const across = Math.max(0, trueWindSpeed) * Math.sin(radians)
  const speed = Math.hypot(along, across)

  return {
    angle: speed <= Number.EPSILON
      ? 0
      : (Math.atan2(across, along) * 180) / Math.PI,
    speed,
  }
}

/**
 * North's 420/470 guides keep the boom close to the centreline through the
 * full-power upwind range, then ease it progressively when overpowered.
 * 420: https://www.northsails.co.jp/wordpress/wp-content/uploads/2026/03/420-M12-Tuning-Guide_j.pdf
 * 470: https://colorcode.northsails.com/sailing/wp-content/uploads/2017/05/470_tuning_guide_e01.pdf
 */
export function closeHauledBoomAngle(boat: BoatClass, windSpeed: number) {
  const underpowered = 1 - inverseLerp(6, 10, windSpeed)
  const overpowered = inverseLerp(12, 18, windSpeed)
  const centrelineAllowance = boat === '420' ? 1.5 : 1
  const lightAirEase = boat === '420' ? 2 : 4
  const heavyAirEase = boat === '420' ? 9 : 8
  return centrelineAllowance + underpowered * lightAirEase + overpowered * heavyAirEase
}

/**
 * Solves the automatic mainsail angle used by the trainer.
 *
 * Reaching trim follows the same idealisation used by Atterwind: hold a
 * target angle of attack to apparent wind. Close-hauled trim is blended into
 * class-guide boom positions because jib upwash, bridle geometry and the
 * mainsail's camber make AWA - AoA alone unsuitable there. The boom is capped
 * at a representative shroud position for broad reaching.
 * https://github.com/flyinggorilla/simulator.atterwind.info
 * https://www.northsails.com/en-it/blogs/north-sails-blog/470-speed-guide
 */
export function optimalMainTrim(
  boat: BoatClass,
  trueWindAngle: number,
  trueWindSpeed: number,
  boatSpeed: number,
): MainTrimSolution {
  const wind = apparentWind(trueWindAngle, trueWindSpeed, boatSpeed)
  const targetAngleOfAttack = 15
  const classGuideAngle = closeHauledBoomAngle(boat, trueWindSpeed)
  const shroudLimit = boat === '420' ? 78 : 80
  const rawFlowAngle = Math.max(0, wind.angle - targetAngleOfAttack)
  const flowBoomAngle = Math.min(rawFlowAngle, shroudLimit)
  const flowBlend = smoothstep(52, 82, trueWindAngle)
  const blendedAngle = lerp(classGuideAngle, flowBoomAngle, flowBlend)
  const boomAngle = clamp(blendedAngle, 0, shroudLimit)
  const atShroud = rawFlowAngle >= shroudLimit && flowBlend === 1

  const mode: MainTrimMode = atShroud
    ? 'shroud-limit'
    : flowBlend === 1
      ? 'attached-flow'
      : flowBlend === 0
        ? 'class-guide'
        : 'transition'

  const label: Record<MainTrimMode, string> = {
    'class-guide': 'クローズ：クラス基準',
    transition: 'クローズから見かけ風へ移行',
    'attached-flow': '見かけ風に迎角15°',
    'shroud-limit': 'ブームはシュラウド位置まで',
  }

  return {
    apparentWind: wind,
    boomAngle,
    flowBoomAngle,
    targetAngleOfAttack,
    mode,
    label: label[mode],
  }
}
